base:
    seed: 1004
    model_arc: 'distilbert'
    num_classes: 2
    input_dir: '../input/nbme-score-clinical-patient-notes'
    output_dir: './results/'
    train_only: False
    max_len: 512
    ckp_path: '../input/nbme-hf-distilbert-2train/train/nbme-case/checkpoint-10432/'
    train_args:
        num_epochs: 7
        train_batch_size: 32
        val_batch_size: 32
        model_path: 'pytorch_model.bin'
        config_path: 'config.json'
        dropout_rate: 0.2 # 0.1~0.3
        max_grad_norm: 1.0
        max_lr: 0.0001
        min_lr: 0.00001
        cycle: 3
        gamma: 0.5
        weight_decay: 0.000001
        log_intervals: 10
        eval_metric: 'accuracy'
        n_splits: 5
